version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        environment: 
            - "discovery.type=single-node"
        ports: 
            - 9200:9200
        networks:
            - elk
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.2
        ports: 
            - 5601:5601
        environment: 
            - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
        networks: 
            - elk
        depends_on: 
            - elasticsearch
    logstash:
        image: docker.elastic.co/logstash/logstash:7.13.2
        volumes: 
            - "./logstash-config:/usr/share/logstash/config"
        depends_on: 
            - elasticsearch
        networks: 
            - elk
networks:
    elk:
