version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        environment: 
            - "discovery.type=single-node"
        ports: 
            - 9200:9200
        networks:
            - elk
networks:
    elk:
